### ISSUE TITLE
我使用了你的模板然后使用 async await 会报错 

### ISSUE THREAD

**Issue by 15521054523** [Larry850806/nodejs-ES7-template#1]
Node: 8.9.1
npm: 5.5.1
cnpm: 6.0.0

![image](https://user-images.githubusercontent.com/19297519/54005540-d2da5500-4194-11e9-8898-93dcde82664d.png)

**Comment by 15521054523** [comment]
附代码
![image](https://user-images.githubusercontent.com/19297519/54005595-fd2c1280-4194-11e9-999c-48226cdafc80.png)

**Comment by Larry850806** [comment]
你好，這個 template 是給 Nodejs 用的哦，所以沒辦法跑在瀏覽器上
